{% set version = '0.4.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-logrx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/logrx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/logrx/logrx_{{ version }}.tar.gz
  sha256: adebb65d3186483a1e4b62153a43203f0536d211658769ece41026c85ef781e5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-digest
    - r-dplyr >=1.0.0
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-sessioninfo >=1.2
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-digest
    - r-dplyr >=1.0.0
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-sessioninfo >=1.2
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('logrx')"           # [not win]
    - "\"%R%\" -e \"library('logrx')\""  # [win]

about:
  home: https://pharmaverse.github.io/logrx/, https://github.com/pharmaverse/logrx
  license: MIT
  summary: A utility to facilitate the logging and review of R programs in clinical trial programming
    workflows.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
